// Generated by CoffeeScript 1.3.3
(function() {
  var DATA_FUNCD_ASYNC, Funcd, attributeList, defaultAttributes, doctypes, elements, escapeHtml, getTemplateFunction, htmlChars, idSequence, mergeElements, mixinShortTag, mixinTag, nextId, rawContentElements, replaceToken, requireEx, tokensToReplace, _,
    __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  if (typeof global !== "undefined" && global !== null) {
    _ = require('underscore');
  } else {
    _ = window._;
  }

  DATA_FUNCD_ASYNC = 'data-funcd';

  requireEx = function(mod, nocache) {
    if (nocache == null) {
      nocache = false;
    }
    if (nocache) {
      delete require.cache[require.resolve(mod)];
    }
    return getTemplateFunction(require(mod));
  };

  idSequence = 0;

  nextId = function() {
    idSequence += 1;
    return "funcd-async-" + idSequence;
  };

  doctypes = {
    'default': '<!DOCTYPE html>',
    '5': '<!DOCTYPE html>',
    'xml': '<?xml version="1.0" encoding="utf-8" ?>',
    'transitional': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">',
    'strict': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">',
    'frameset': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">',
    '1.1': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">',
    'basic': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.1//EN" "http://www.w3.org/TR/xhtml-basic/xhtml-basic11.dtd">',
    'mobile': '<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.2//EN" "http://www.openmobilealliance.org/tech/DTD/xhtml-mobile12.dtd">',
    'ce': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "ce-html-1.0-transitional.dtd">'
  };

  elements = {
    full: 'a abbr address article aside audio b bdi bdo blockquote body button\
 canvas caption cite code colgroup datalist dd del details dfn div dl dt em\
 fieldset figcaption figure footer form h1 h2 h3 h4 h5 h6 head header hgroup\
 html i iframe ins kbd label legend li map mark menu meter nav noscript object\
 ol optgroup option output p pre progress q rp rt ruby s samp script section\
 select small span strong sub summary sup table tbody td textarea tfoot\
 th thead time title tr u ul video',
    short: 'area base br col command embed hr img input keygen link meta param\
 source track wbr',
    obsoleteFull: 'applet acronym bgsound dir frameset noframes isindex listing\
 nextid noembed plaintext rb strike xmp big blink center font marquee multicol\
 nobr spacer tt',
    obsoleteShort: 'basefont frame'
  };

  defaultAttributes = {
    script: {
      type: "text/javascript"
    }
  };

  rawContentElements = ['script'];

  mergeElements = function() {
    var arg, args, element, result, _i, _j, _len, _len1, _ref;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    result = [];
    for (_i = 0, _len = args.length; _i < _len; _i++) {
      arg = args[_i];
      _ref = arg.split(' ');
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        element = _ref[_j];
        if (__indexOf.call(result, element) < 0) {
          result.push(element);
        }
      }
    }
    return result;
  };

  escapeHtml = function(value) {
    if (!value) {
      return "";
    }
    return value.replace(htmlChars, replaceToken);
  };

  tokensToReplace = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': "&quot;",
    "'": "&#39;"
  };

  replaceToken = function(token) {
    return tokensToReplace[token] || token;
  };

  htmlChars = /[&<>"']/g;

  attributeList = function(tag, obj) {
    var attributes, list, name, val;
    if (obj == null) {
      obj = {};
    }
    attributes = defaultAttributes[tag] ? _.extend(_.clone(defaultAttributes[tag]), obj) : obj;
    list = '';
    for (name in attributes) {
      val = attributes[name];
      list += " " + name + "=\"" + (escapeHtml(val)) + "\"";
    }
    return list;
  };

  mixinTag = function(tag) {
    return Funcd.prototype[tag] = function(attributes, inner) {
      var options;
      options = {
        tag: tag,
        parseBody: true,
        parseAttributes: true
      };
      return this._outerHtml(options, attributes, inner);
    };
  };

  mixinShortTag = function(tag) {
    return Funcd.prototype[tag] = function(attributes) {
      var attrList;
      attrList = "";
      if (_.isObject(attributes)) {
        attrList = attributeList(tag, attributes);
      }
      return this.buffer += this.lead + ("<" + tag + attrList + "/>") + this.eol;
    };
  };

  getTemplateFunction = function(template) {
    if (typeof template === "function") {
      return template;
    } else if (typeof template.main === "function") {
      return template.main;
    } else {
      throw new Error("template argument must be an object or function");
    }
  };

  Funcd = (function() {

    function Funcd(opts) {
      var fn, name, self, _fn, _ref, _ref1;
      if (opts == null) {
        opts = {};
      }
      this.pretty = (_ref = opts.pretty) != null ? _ref : false;
      this.options = opts;
      self = this;
      if (opts.mixins) {
        _ref1 = opts.mixins;
        _fn = function(name, fn) {
          return self[name] = function() {
            var args;
            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            return fn.apply(self, [self].concat(args));
          };
        };
        for (name in _ref1) {
          fn = _ref1[name];
          _fn(name, fn);
        }
      }
      this.lead = '';
      this.blocks = {};
      this.eol = this.pretty ? '\n' : '';
      this.buffers = [];
      this.asyncCallbacks = [];
      this.buffer = "";
    }

    Funcd.prototype.applyAsyncCallbacks = function($parent) {
      var pair, _i, _len, _ref, _results;
      if (!this.asyncCallbacks) {
        return;
      }
      _ref = this.asyncCallbacks;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pair = _ref[_i];
        _results.push(pair.lambda(jQuery('#' + pair.id)));
      }
      return _results;
    };

    Funcd.prototype.block = function(name, attributes, inner) {
      var exists, options;
      this.buffers.push(this.buffer);
      this.buffer = "";
      options = {
        tag: null,
        parseBody: true,
        parseAttributes: false
      };
      this._outerHtml(options, attributes, inner);
      exists = this.blocks[name];
      this.blocks[name] = this.buffer;
      this.buffer = this.buffers.pop();
      if (exists == null) {
        return this.buffer += this.lead + ("___" + name + "___") + this.eol;
      }
    };

    Funcd.prototype.doctype = function(s) {
      return this.buffer += doctypes[s.toString()] + this.eol;
    };

    Funcd.prototype["extends"] = function(template) {
      if (typeof template === "string" && (typeof require !== "undefined" && require !== null)) {
        template = requireEx(template, this.options.nocache);
      } else {
        template = getTemplateFunction(template);
      }
      return template(this);
    };

    Funcd.mixin = function(mixins) {
      var fn, name, _results;
      _results = [];
      for (name in mixins) {
        fn = mixins[name];
        _results.push((function(name, fn) {
          return Funcd.prototype[name] = function() {
            var args;
            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            return fn.apply(this, [this].concat(args));
          };
        })(name, fn));
      }
      return _results;
    };

    Funcd.prototype._raw = function(s) {
      return {
        __raw: s
      };
    };

    Funcd.prototype.render = function() {
      var args, template;
      template = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (typeof template === 'function') {
        return template.apply(null, [this].concat(__slice.call(args)));
      } else if (typeof template.main === 'function') {
        return template.main.apply(template, [this].concat(__slice.call(args)));
      } else {
        return this.text(template.toString());
      }
    };

    Funcd.renderBuilder = function() {
      var args, builder, first, options, template;
      options = arguments[0], template = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      args = [].slice.call(arguments);
      first = args[0];
      if (_.isFunction(first.main)) {
        template = first.main;
        options = {};
        args = args.slice(1);
      } else if (_.isFunction(first)) {
        template = first;
        options = {};
        args = args.slice(1);
      } else if (_.isString(first)) {
        template = requireEx(first);
        options = {};
        args = args.slice(1);
      } else if (_.isObject(first)) {
        options = first;
        template = _.isFunction(args[1]) ? args[1] : requireEx(args[1], options.nocache);
        args = args.slice(2);
      }
      builder = new Funcd(options);
      template.apply(builder, [builder].concat(args));
      return builder;
    };

    Funcd.render = function() {
      var args, builder;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      builder = this.renderBuilder.apply(this, args);
      return builder.toHtml();
    };

    Funcd.prototype.raw = function(s) {
      return this.buffer += s;
    };

    Funcd.prototype.text = function(s) {
      return this.buffer += escapeHtml(s);
    };

    Funcd.prototype.toHtml = function() {
      var innerHtml, k, that, _ref;
      _ref = this.blocks;
      for (k in _ref) {
        innerHtml = _ref[k];
        this.buffer = this.buffer.replace(RegExp("___" + k + "___", "g"), innerHtml);
      }
      if (this.asyncCallbacks) {
        that = this;
        setTimeout(function() {
          return that.applyAsyncCallbacks();
        }, 1);
      }
      return this.buffer;
    };

    Funcd.compile = function(filenameOrObject) {
      return function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return Funcd.render.apply(Funcd, [filenameOrObject].concat(__slice.call(args)));
      };
    };

    Funcd.prototype._outerHtml = function(options, attrs, inner) {
      var arg, asyncfn, attributes, innerHtmlFn, innerText, parseAttributes, parseBody, tag, _i, _len, _ref;
      tag = options.tag, parseAttributes = options.parseAttributes, parseBody = options.parseBody;
      attributes = "";
      innerText = "";
      innerHtmlFn = null;
      _ref = [attrs, inner];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        arg = _ref[_i];
        switch (typeof arg) {
          case 'string':
            if (rawContentElements.indexOf(tag) < 0) {
              innerText += escapeHtml(arg);
            } else {
              innerText += arg;
            }
            break;
          case 'number':
            innerText += escapeHtml(arg.toString());
            break;
          case 'function':
            innerHtmlFn = arg;
            break;
          case 'object':
            if (arg.__raw) {
              innerText = arg.__raw;
            } else {
              if (parseAttributes) {
                if (arg[DATA_FUNCD_ASYNC]) {
                  asyncfn = arg[DATA_FUNCD_ASYNC];
                  delete arg[DATA_FUNCD_ASYNC];
                  if (!arg.id) {
                    arg.id = nextId();
                  }
                  this.asyncCallbacks.push({
                    lambda: asyncfn,
                    id: arg.id
                  });
                }
                attributes += attributeList(tag, arg);
              } else if (arg) {
                innerText += arg.toString();
              }
            }
        }
      }
      if (parseAttributes && attributes === "" && defaultAttributes[tag]) {
        attributes += attributeList(tag);
      }
      if (tag) {
        this.buffer += this.lead + ("<" + tag + attributes + ">" + this.eol);
      }
      if (parseBody) {
        if (this.pretty) {
          this.lead += '  ';
        }
        if (innerText.length > 0) {
          this.buffer += this.lead + innerText + this.eol;
        }
        if (innerHtmlFn != null) {
          innerHtmlFn.apply(this);
        }
        if (this.pretty) {
          this.lead = this.lead.slice(0, -2);
        }
      }
      if (tag) {
        return this.buffer += this.lead + ("</" + tag + ">" + this.eol);
      }
    };

    return Funcd;

  })();

  if (typeof jQuery !== "undefined" && jQuery !== null) {
    jQuery.fn.funcd = function(template, args) {
      return this.each(function() {
        var $obj, builder;
        $obj = jQuery(this);
        builder = Funcd.renderBuilder(template);
        return $obj.html(builder.toHtml());
      });
    };
  }

  (function() {
    var tag, _i, _j, _len, _len1, _ref, _ref1;
    _ref = mergeElements(elements.full, elements.obsoleteFull);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tag = _ref[_i];
      mixinTag(tag);
    }
    _ref1 = mergeElements(elements.short, elements.obsoleteShort);
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      tag = _ref1[_j];
      mixinShortTag(tag);
    }
    if (typeof global !== "undefined" && global !== null) {
      return module.exports = Funcd;
    } else {
      return window.Funcd = Funcd;
    }
  })();

}).call(this);
